language: node_js
node_js:
 - "8.11"

branches:
  only:
    - master

before_script:
  - yarn global add @angular/cli
  - yarn global add http-server
  - yarn global add wait-on

cache:
  yarn: true
  directories:
    - node_modules

script:
  - ng lint
  - ng build --prod
  - http-server dist/ &
  - yarn lh