// Writes src/code-theme.css: one class per color in the Shiki theme used by src/app/shared/markdown.ts,
// matching the classes its style-to-classes transformer puts on highlighted code.
// Run after changing CODE_THEME: npm run generate:code-theme
import { writeFileSync } from 'node:fs';
import type { ThemeRegistrationRaw } from 'shiki/core';

const themeName = 'github-light';
const theme: ThemeRegistrationRaw = (await import(`shiki/themes/${themeName}.mjs`)).default;

const foreground = (theme.fg ?? theme.colors?.['editor.foreground'] ?? '#000').toLowerCase();
const colors = new Set([foreground]);
for (const rule of theme.tokenColors ?? []) {
    if (rule.settings.foreground) {
        colors.add(rule.settings.foreground.toLowerCase());
    }
}

const css = [
    `/* Generated by scripts/generate-code-theme.mts from Shiki's ${themeName} theme. Don't edit by hand. */`,
    `.shiki { color: ${foreground}; }`,
    ...[...colors].map((color) => `.sk-${color.slice(1)} { color: ${color}; }`),
    '.sk-italic { font-style: italic; }',
    '.sk-bold { font-weight: bold; }',
    '.sk-underline { text-decoration: underline; }',
    '.sk-line-through { text-decoration: line-through; }',
    '',
].join('\n');

writeFileSync(new URL('../src/code-theme.css', import.meta.url), css);
console.log(`Wrote src/code-theme.css with ${colors.size} colors`);
